# ATP Test Case ID: SE_15
# Excel: Hamburger Menu 15 | Module: Initialization
# Verify Log In & Navigate to Account Settings
# Expected: User is redirected to HM_02A - Account Settings screen successfully.
appId: com.hp.impulse.sprocket
name: "SE_15 - Verify Log In Navigate to Account Settings"
tags:
  - settings
  - atp-excel
---
- runFlow: subflows/login_from_hamburger_email_valid.yaml
- runFlow: subflows/open_hamburger_menu.yaml
- tapOn: ".*(?i)Account Settings.*"
- waitForAnimationToEnd:
    timeout: 3000
- runFlow: subflows/assert_account_settings_screen.yaml
